services:
  clients-router:
    image:    registry.gitlab.com/rny3/brande/clients_router:latest
    ports:    ["80:80", "443:443", "443:443/udp"]
    volumes:  [router_data:/data, router_config:/config]
    networks: [qabu_network]
    secrets:  [cloudflare_api_token, fb_dispatcher_secret]

  auth-verifier:
    image:    registry.gitlab.com/rny3/brande/auth_verifier:latest
    networks: [qabu_network]
    secrets:  [jwt_signing_key]

  provisioner:
    image:    registry.gitlab.com/rny3/brande/provisioner:latest
    networks: [qabu_network]
    secrets:  [provision_secret]
    volumes:
      - ..:/app/qabu

volumes:
  router_data:
  router_config:

networks:
  qabu_network: {name: qabu_network}

secrets:
  cloudflare_api_token: {file: ./secrets/cloudflare_api_token.secret}
  fb_dispatcher_secret: {file: ./secrets/fb_dispatcher_secret.secret}
  jwt_signing_key:      {file: ./secrets/jwt_signing_key.secret}
  provision_secret:     {file: ./secrets/provision_secret.secret}
