services:
  router:
    image:    registry.gitlab.com/rny3/brande/router:v0.0.20
    ports:    ["80:80", "443:443", "443:443/udp"]
    volumes:  [router_data:/data, router_config:/config]
    networks: [qabu_network]
    secrets:  [cloudflare_api_token]
    # secrets:  [cloudflare_api_token, fb_dispatcher_secret]

volumes:
  router_data:
  router_config:

networks:
  qabu_network: {name: qabu_network}

secrets:
  cloudflare_api_token: {file: ./secrets/cloudflare_api_token.secret}
  # fb_dispatcher_secret: {file: ./secrets/fb_dispatcher_secret.secret}
