services:

  services-router:
    image: registry.gitlab.com/rny3/brande/services_router:latest
    networks: [client_network, qabu_network]
    volumes:
      - ./assets:/srv/assets:ro

  site:
    image: registry.gitlab.com/rny3/brande/site:latest
    networks: [client_network]
    volumes:
      - ./assets:/site/assets
      - ../shared/widget/widget.js:/site/widget.js:ro

  prompt-composer:
    image: registry.gitlab.com/rny3/brande/prompt_composer:latest
    networks: [client_network]
    secrets: [gemini_1, gemini_2, groq_1, groq_2, admin_secret]
    volumes: [./data/:/app/data]

  admin:
    image: registry.gitlab.com/rny3/brande/admin:latest
    networks: [client_network]
    secrets: [authorized_emails, admin_secret]
    volumes:
      - ./assets:/app/assets:ro
      - ./data:/app/data
      - ../shared/widget/widget.js:/app/public/widget.js:ro

  mock-facebook:
    image: registry.gitlab.com/rny3/brande/mock_facebook:latest
    networks: [client_network]
    volumes: [./assets/mock_facebook/:/app/data/]

  facebook-comments:
    image: registry.gitlab.com/rny3/brande/facebook_comments:latest
    networks: [client_network]
    secrets: [fb_page_access_token]
    environment: [FACEBOOK_API_URL=https://graph.facebook.com/v24.0/]

  # facebook-dm:
  #   image: registry.gitlab.com/rny3/brande/facebook_dm:latest
  #   networks: [client_network]
  #   secrets: [fb_page_access_token]
  #   environment: [FACEBOOK_API_URL=https://graph.facebook.com/v24.0/]

networks:
  client_network:
  qabu_network:   {external: true}

secrets:
  authorized_emails:    {file: ./secrets/authorized_emails.json}
  gemini_1:             {file: ./secrets/gemini_1.secret}
  gemini_2:             {file: ./secrets/gemini_2.secret}
  groq_1:               {file: ./secrets/groq_1.secret}
  groq_2:               {file: ./secrets/groq_2.secret}
  fb_page_access_token: {file: ./secrets/fb_page_access_token.secret}
  admin_secret:         {file: ./secrets/admin_secret.secret}
