server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.php$ { return 444; }
    location ~ /\.git { return 444; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
